### ISSUE TITLE
ansible-conda-env and ansible-miniconda should mention one another in the README

### ISSUE THREAD

**Issue by cwells** [andrewrothstein/ansible-conda-env#11]
I initially bypassed your ansible-miniconda module because it didn't manage environments. It turns out that GitHub search won't find "miniconda" if you search for "conda" (and obviously the reverse), so I had completely missed the existence of this repo.

In any case, it would be helpful if these two projects could mention the existence of the other, as these modules appear to be by far the most complete and well-maintained.

**Comment by andrewrothstein** [comment]
thanks for letting me know. I added comments to the READMEs.
