### ISSUE TITLE
Documentation on how to install env and then install packages within that env

### ISSUE THREAD

**Issue by antunderwood** [andrewrothstein/ansible-conda-env#5]
Thanks you for this ansible role and other roles that allow conda functionality for ansible.
I'm a bit confused as to the playbook syntax for create a conda env and then installing packages to that env.

Would you be able to provide some shorter extra docs please. Much appreciated.
Thanks again.

**Comment by andrewrothstein** [comment]
the idea is that you have the yaml file that corresponds to your environment and this role places it on the host, and creates a conda environment therefrom. if u look in the role defaults, it assumes your Anaconda distribution is at /usr/local/anaconda.  my [luigi role]( https://github.com/andrewrothstein/ansible-luigi) is a pretty simple example of how to use it in a role.
